### ISSUE TITLE
Citation styles

### ISSUE THREAD

**Issue by mfenner** [force11/force11-scwg#100]
Citations in text follow the citation style used. Two practical recommendations (which might already be work for the implementation group) are: a) include version information, and b) include a label to indicate that it is software, e.g. `[Software]`.

**Comment by danielskatz** [comment]
Can you make a specific change suggestion via a pull request?

**Comment by mfenner** [comment]
will do after the call.

**Comment by danielskatz** [comment]
@mfenner just a reminder of this - if you can do it in the next 24 hours, that would be great!

**Comment by mfenner** [comment]
@danielskatz will put my suggested text here:

> Citations in the scholarly literature are formatted according to the citation style used by that publication (journal, etc.). As these citations are typically sent to publishers not as structured metadata, but as text formatted in that citation style, and because the citation style dictates how the human reader sees the software citation, we recommend that all citation styles supports the following: a) a label indicating that this is software, e.g. `[Computer program]` and b) support for version information, e..g `Version 1.8.7`.

**Comment by mfenner** [comment]
This is consistent with the discussion around data citations. Please rephrase as appropriate.

**Comment by danielskatz** [comment]
addressed by a change in 5 in https://github.com/force11/force11-scwg/commit/e9293f49ec72f4112724de89a48a00f1bfcb7034
