### ISSUE TITLE
need to write an abstract

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-scwg#101]
We need to write an abstract before Force2016.

**Comment by arfon** [comment]
@danielskatz I had a go at this here: https://github.com/force11/force11-scwg/commit/fc061026d9b6d0a040ca8291c4cc90319b048d8c

**Comment by danielskatz** [comment]
Force should be FORCE, and there's a cite of the data document elsewhere, so you should just be able to find it and get the right ref there - otherwise looks good

(I would do this, but I'm just boarding a flight to get to FORCE2016)

**Comment by kyleniemeyer** [comment]
I made a few fixes, and removed the ref for data citation (for now at least)—I feel like the abstract should be standalone without any external references.

I’m also going to make this a single paragraph.

Kyle

**Comment by arfon** [comment]
OK thanks for the comments/edits both.
