### ISSUE TITLE
section 6 is empty

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-scwg#102]
we don't have any examples of how the principles would be applied to the use cases, which we were going to do

**Comment by sctchoi** [comment]
Perhaps we could change it to a section of conclusion and future work, in which we mention implementation examples as future work.

**Comment by kyleniemeyer** [comment]
Addressed in a774c97aba103bca6c21f46720c288981f531feb

**Comment by kyleniemeyer** [comment]
And some edits in 6d0628dae3ea0c638a6e433113e31b08aad7d720. At this point, I think this issue is addressed, although revisions to the new section are welcome.

**Comment by danielskatz** [comment]
and further edits in https://github.com/force11/force11-scwg/commit/1f806d3cca98ae6c3b0102b3439d045161fb12a4
