### ISSUE TITLE
Should we include branch info in software citation?

### ISSUE THREAD

**Issue by sctchoi** [force11/force11-scwg#103]
Recently I work with a development branch code in GitHub to compute something rather than the latest release/master branch code. I wonder if we need to add "branch" information in software citation?

**Comment by arfon** [comment]
That's too close to the implementation for my liking, i.e. that's a Git- specific detail.

In this case the Git sha would also capture this information?

**Comment by migueldvb** [comment]
From the git branch documentation you could figure out the branch that contains a given commit with this command:

```
git branch --contains <commit>
```

**Comment by danielskatz** [comment]
I agree that this is not needed in general, and it might be incorrect over time, though there are probably some cases where it would help.  Overall, I suggest not including it.
