### ISSUE TITLE
Comment from Catherine Jones in chat

### ISSUE THREAD

**Issue by arfon** [force11/force11-scwg#104]
> I have to go soon, so I wanted to make a general comment about the principles, section 2.  The term "science/scientific" is used a lot through this section.  Here in the UK this term has a meaning which restricts this to physical sciences and excludes social sciences, art & humanities.  The term "research" tends to be used in these circumstances. I believe that these principles apply to all domains, so maybe the wording should be considered. I appreciate this may by a UK only cultural issue.  I was on a data policy committee where this was a very touchy issue.

**Comment by arfon** [comment]
"Research" seems to be the suggested change.

**Comment by danielskatz** [comment]
addressed in https://github.com/force11/force11-scwg/commit/a4092b270d04a367ce8cbdad915cfdeb25407f71
