### ISSUE TITLE
Recommended vs. required/minimal metadata for use cases

### ISSUE THREAD

**Issue by kyleniemeyer** [force11/force11-scwg#108]
Based on comments from the 5 April call and some in the [Use Cases Google Doc](https://docs.google.com/document/d/1dS0SqGoBIFwLB5G3HiLLEOSAAgMdo8QPEpjYUaWCvIU/edit#), there is some interest in differentiating between metadata for each use case that we see as required/minimal and what we recommend.

My suggestion is that we use an open circle (LaTeX: `\textopenbullet`) for the "optional" recommended metadata. 

There are already some suggestions:
- @mfenner and @owlice suggested adding description/abstract/readme as recommended
- @ljhwang suggested that license may become recommended (rather than required) for most

Since this may involve some discussion, perhaps rather than issuing PRs people can make additional suggestions or comments here.

**Comment by mfenner** [comment]
+1 regarding `license` as recommended rather than required.

**Comment by mfenner** [comment]
In terms of discovery of scientific software another useful feature would be keywords/tags, e.g. `python` or `astronomy`.

**Comment by kyleniemeyer** [comment]
OK, I addressed the suggested changes in 7fdef9d33d29c20672c563e145e0622b4031a3e9, by adding a recommended category via `\textopenbullet`. I made `license` recommended where it showed up, and also changed `contributor role` (using some editorial discretion).

Following the recommendations of @mfenner and @owlice, I added columns for `Description` and `Keywords` that became recommended where I thought appropriate. I also added some explanation for each of those to the text, although they're fairly self-explanatory.

Please take a look, and see if you agree with my changes. I'm hoping to close this issue soon (and also hoping that my changes don't cause more harm than good).

**Comment by kyleniemeyer** [comment]
I'm going to mark this as "will close soon", although I'll back off that if there is any additional discussion.
