### ISSUE TITLE
Discussion items

### ISSUE THREAD

**Issue by CaroleGoble** [force11/force11-scwg#110]
Aspects that  we should to make some reference to in the discussion even if its just to rule out of scope:
- what we mean by software - source code? compiled code? VM? execution environment this is discussed quite well in
  http://rrr.cs.st-andrews.ac.uk/wp-content/uploads/2015/10/guidelines-software-identification.pdf
  http://www.software.ac.uk/blog/2016-03-29-reproducible-research-citing-your-execution-environment-using-docker-and-doi?bw
- Citation semantics for changeable objects:
  - locating software
  - snapshot of software at the time of publication
- Citation challenges of foreground and background software
- Data Citation Implementation is spending time on the JATS extensions for data, and on publisher workflows. Should we mention JATS?
- The need to educate publishers and reviewers -> as the examples in Mike Jackson's excellent Blog point out.
- The challenge of who is an author of software

**Comment by danielskatz** [comment]
The first bullet has been addressed by a new subsection in 5 in https://github.com/force11/force11-scwg/commit/6f9358512e6f3dacfa1b849036c414beae75b215

**Comment by danielskatz** [comment]
@CaroleGoble: what do you mean by "foreground and background software"?

**Comment by CaroleGoble** [comment]
I'm referring to Christine Borgmans characterisation - folks cite the software or dataset that is in the foreground of their research but are much less likely to cite that that is in the background. Like platforms or infrastructure. They cite a tool but not the workflow system for example. And never the repository.

Carole

Sent from my iPhone by
Professor Carole Goble
The University of Manchester
UK

On 17 Apr 2016, at 23:25, "Daniel S. Katz" <notifications@github.com<mailto:notifications@github.com>> wrote:

@CaroleGoblehttps://github.com/CaroleGoble: what do you mean by "foreground and background software"?

**Comment by danielskatz** [comment]
I think we somewhat cover this in the discussion of derived software in 5, currently 5.3.  But your point is a bit different too.  Do you have some specific text change that you think we should make, there or elsewhere?

**Comment by CaroleGoble** [comment]
Sorry to be slow on this....do you still need some text?

**Comment by danielskatz** [comment]
If you have a specific suggestion, yes.  Or at this point, we could close this issue and you could just follow the comment process shown on https://www.force11.org/software-citation-principles

**Comment by CaroleGoble** [comment]
I'll do it in the comment process so then there is one clean mechanism

**Comment by danielskatz** [comment]
Thanks - I'll close this issue then.
