### ISSUE TITLE
Additional material and community actions

### ISSUE THREAD

**Issue by CaroleGoble** [force11/force11-scwg#111]
sciencecodemanifesto.org set out principles including citation

sect 4.1 there have been numerous workshops on reproducibility which have included software and data citation
the latest in the UK was the Alan Turing Institute Symposium on Reproducibility last week.

sect 4.2 the NIH report was also put out to public comment

sect 4.3
other efforts on metadata standards include:
- researchobject.org (:-))
- The Software Ontology http://theswo.sourceforge.net/   http://jbiomedsem.biomedcentral.com/articles/10.1186/2041-1480-5-25
- EDAM Ontology (used by ELIXIR and incorporating the Software Ontology)

5.6 we should mention of RRID which is a Force11 activity

**Comment by danielskatz** [comment]
This is mostly for the related work section, so I'm assigning it to Arfon, except the RRID comment that I made a new issue (https://github.com/force11/force11-scwg/issues/114) and discussed there, then resolved with adding text in https://github.com/force11/force11-scwg/commit/d55c72253fdb81bb3b05fcfc3616c09588aeda16 and then closed https://github.com/force11/force11-scwg/issues/114

**Comment by arfon** [comment]
> sciencecodemanifesto.org set out principles including citation

Addressed in bb48bab53f9bfc78f07b279acc5627228d7792fe

**Comment by arfon** [comment]
Fixed in 26a970350548c9fc83a72459dfe42826e6949293
