### ISSUE TITLE
 Policy makers are another stakeholder. 

### ISSUE THREAD

**Issue by CaroleGoble** [force11/force11-scwg#112]
Policy makers are another stakeholder.

**Comment by danielskatz** [comment]
Are you suggesting another row in Table 2?  If so, can you say what the values in the other columns would be?

If not, what change would you suggest?

**Comment by arfon** [comment]
@CaroleGoble - is this very different from 'Funder' as currently listed? If the requirements are the same then perhaps we should list this as 'Funder/Policy maker'?

**Comment by ashleysa** [comment]
Yes, I think that Policy Maker should be its own line, in addition to Funder. 
wants to (a draft): Understand how software contributes to research
(kind of a looking to the future instead of the past like the funder is currently described)

**Comment by ashleysa** [comment]
OR, based on continued discussion:
Policy Makers and Funders both broadly want to understand how software has been used/is being/could be used within academia. 

A second use case, if we decide to include: is that of compliance. This would be Funder: wants to check compliance with software creation/sharing/accessibility requirements.

**Comment by CaroleGoble** [comment]
Sounds sensible

Carole

Sent from my iPhone by
Professor Carole Goble
The University of Manchester
UK

On 17 Apr 2016, at 10:29, "Arfon Smith" <notifications@github.com<mailto:notifications@github.com>> wrote:

@CaroleGoblehttps://github.com/CaroleGoble - is this very different from 'Funder' as currently listed? If the requirements are the same then perhaps we should list this as 'Funder/Policy maker'?

**Comment by CaroleGoble** [comment]
We also need to show policy makers that software is important and worth investing in as key infrastructure.
You'd be surprised how hard that is to get across.

Carole

Sent from my iPhone by
Professor Carole Goble
The University of Manchester
UK

On 17 Apr 2016, at 11:16, "Ashley E. Sands" <notifications@github.com<mailto:notifications@github.com>> wrote:

OR, based on continued discussion:
Policy Makers and Funders both broadly want to understand how software has been used/is being/could be used within academia.

A second use case, if we decide to include: is that of compliance. This would be Funder: wants to check compliance with software creation/sharing/accessibility requirements.

**Comment by kyleniemeyer** [comment]
Can this discussion be crystallized into a solid suggested addition/change? (or better yet a pull request!)

**Comment by kyleniemeyer** [comment]
To minimally address this issue, I added `policy maker` to the use case `Show how funded software has been used` in a45daa76b9536475a5aa5a169df64d7fda2a14bc.

To @ashleysa's suggestion of a funder use case "check compliance with software creation/sharing/accessibility requirements", I worry that it may be out of scope, because we don't know what the requirements would be.

**Comment by kyleniemeyer** [comment]
I'm going to say this one has been addressed (at least on the "policy maker" side), unless there are any concrete suggestions or a PR for a new use case.

**Comment by arfon** [comment]
> I'm going to say this one has been addressed (at least on the "policy maker" side), unless there are any concrete suggestions or a PR for a new use case.

👍
