### ISSUE TITLE
discuss RRIDs?

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-scwg#114]
@CaroleGoble wrote in https://github.com/force11/force11-scwg/issues/111
5.6 we should mention of RRID which is a Force11 activity

I'm separating this out, so the main part of that issue, on Related Work, can be assigned to Arfon

**Comment by danielskatz** [comment]
@CaroleGoble,
Which Force11 group are you referring to?

I have some concern with the use of RRIDs for software, since they don't refer to a particular version of software (i.e., they don't have the unique identifier property), which is what we say should be cited.  I think DOIs are much more appropriate for software citation, which is why we recommend them.

What specific text do you think we should add in 5.6?

Thanks!

**Comment by wakibbe** [comment]
I completely agree. For software in a code repository, and therefore under version control, the best practice should be, IMO, creating a DOI to a release in that repository. GitHub for instance supports this. I would recommend against using RRIDs when DOIs to the software are available.

**Comment by danielskatz** [comment]
I've added a bit of text in 5 in https://github.com/force11/force11-scwg/commit/d55c72253fdb81bb3b05fcfc3616c09588aeda16 to hopefully resolve this.
