### ISSUE TITLE
what does an identifier point to?

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-scwg#115]
Discuss the issue that an identifier can point to a specific version, and this is what we mostly were thinking here.  There are also other use cases that are valid, such as identifiers that point to a collection of versions of software, or identifiers that point to the latest version.

One of the drivers behind a collection is to be able to follow and obtain credit for a total software package.

**Comment by mbjones** [comment]
This issue has been addressed by parts of the data repository community, and is reflected in the [DataONE](http://dataone.org) federation of repositories as a distinction between a `PID` (Persistent Identifier) and a `SID` (Series Identifier).  The `PID` references a specific immutable version of an object, whereas the `SID` references a chain of versions of the object, and when resolved always resolves to the latest versioned `PID`.  Some details of this are described in the [DataONE documentation](http://purl.dataone.org/architecture-dev/design/ContentImmutability.html).

**Comment by danielskatz** [comment]
maybe talk about the fact that we are focused on citation here, not reproducibly or credit as much?

**Comment by danielskatz** [comment]
tied to https://github.com/force11/force11-scwg/issues/98

**Comment by danielskatz** [comment]
subsubsection added in 5 (in https://github.com/force11/force11-scwg/commit/23208d255534b220ee3c0372b682a98128fb0f59) to address this.
