### ISSUE TITLE
explain that this is for source code citation specifically, not more general software citation

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-scwg#116]

**Comment by maltman** [comment]
Having made this comment at the workshop, I'll addend:
- Consider in the glossary entries for software binary/software source
- Consider a less strong normative recommendation that source be cited when possible vs. a constraint on domain of citation
- If this does apply only to source -- make it clear in the discussion of use cases that citations to closed source software is out of scope in the

**Comment by danielskatz** [comment]
After reviewing the principles, which I believe apply to the citation of software in any form, I also recognize that the discussion is less general.  So, I've added the following in a new subsection in 5 in https://github.com/force11/force11-scwg/commit/6f9358512e6f3dacfa1b849036c414beae75b215

> Types of software
> 
> The principles and discussion in this document have generally been written to focus on software
> as source code.  However, we recognize that some software is only available as an executable or as a container, while other software may be available as a service.  We believe the principles apply to all of these forms of software, though the implementation of them will certainly differ based on software type.  When software exists as both source code and another type, we recommend that the source code be cited.
