### ISSUE TITLE
Document which use cases are in scope and whether principles sufficient

### ISSUE THREAD

**Issue by maltman** [force11/force11-scwg#120]
The use case section appears to refer to use cases that are not within the scope (or entirely within) the recommendation. For example "show how funded software has been used" seems to relate to citing a series of software, not a specific version. It is not clear that citing a series is in scope. 

Recommend to indicate for each use case whether (a) the use case is in the scope of the recommendations (b) if in scope, whether principles are necessary vs. sufficient for citation wrt to use case

**Comment by kyleniemeyer** [comment]
I certainly agree that some (if not most) use cases go beyond citation itself, in the sense of citing software in a paper—which is really only one use case. This was actually on purpose.

Regarding the specific use case you mentioned, I don't think "show how funded software has been used" necessarily requires citing series or collections of software. I could see a set of identifiers for software (and papers, etc.) being given as "outputs" or "deliverables" from a funded project, and the set of citations or impact being used. Of course, being able to cite a collection might make this easier—I just don't think it's necessary.

**Comment by maltman** [comment]
Suppose the versions the series cited encompasses versions that are not yet created and/or not known at time of publications.  E.g. if grant XXX was used to support the creation of FooBar (v1) -- and funder wishes to understand the impact of FooBar generally (including future versions derived from v1 though not directly funded). 

Similarly one scenario in "Find software to implement task " might be to develop a review article, another a pedagogical document. In both cases, the intent is not to refer to a specific version (or set) but to either a series/branch or the "head" of that series: e.g. "FluxTools is an excellent package for performing flux capacitation analysis in R 3.X)

**Comment by kyleniemeyer** [comment]
There is current text is section 5.7 that may actually resolve your concerns:

> While we often need to cite a specific version of software, we may also need a way to cite the software in general, or the latest version, and to link multiple releases together, perhaps for the purpose of understand citations to the software. The principles in §1 are intended to be applicable at all levels, and to all types of identifiers, such as DOIs, RRIDs, etc., though we again recommend when possible the use of DOIs that identify specific versions of source code.

Since we mention that our principles also apply to citing the software in general (i.e., the collection of all versions), I think your use cases are actually in scope—so I'm going to mark this as "to be closed", unless @maltman (vehemently) disagrees 😄.
