### ISSUE TITLE
Extend discussion of software metadata needs

### ISSUE THREAD

**Issue by mbjones** [force11/force11-scwg#121]
The current section **Existing efforts around metadata standards** discusses several software metadata efforts, but doesn't clearly articulate that a consolidation effort is needed.  Projects like [CodeMeta](http://github.com/codemeta/codemeta) are attempting to to crosswalk software metadata specifications for interoperability, and this section should highlight the need for this while clarifying that it is out of scope for these citation principles.  I am willing to draft a pull request with a short edit to this section.

**Comment by kyleniemeyer** [comment]
Agreed—rather than get into the weeds on this topic here, we should point to CodeMeta.

**Comment by danielskatz** [comment]
@mbjones can we close this now?
