### ISSUE TITLE
Revise principles to clarify implications for citation limits / page limits

### ISSUE THREAD

**Issue by jmcmurry** [force11/force11-scwg#122]
It will always be the responsibility of reviewers to police whether citations are appropriate. Principles should be clear that citation limits should accommodate rather than stifle software citation (and resource citation, and data citation).

**Comment by danielskatz** [comment]
added a new subsection in 5 (Citation limits) in https://github.com/force11/force11-scwg/commit/aeee84e06fbe167deb6386855155d36540342b21 to address this.  Comments welcome.

**Comment by mfenner** [comment]
There is a distinction between citations shown in the human-readable version of a paper, and what is in the metadata. It should be up to the publisher how they display citations, not only the number of citations, but also whether they have a special label to indicate software, or separate reference lists for data and software.

Having software citations in the human readable version of a paper is important, but having the software citation in the metadata sent to Crossref is essential.

**Comment by danielskatz** [comment]
I agree with you, but was trying to keep things as simple as possible - perhaps too simple.

Can you suggest wording changes that would better express this?

**Comment by mfenner** [comment]
Maybe the following:

> This set of software citation principles, if followed, will cause the number of software citations in scholarly products to increase, thus causing the number of overall citations to increase. Some scholarly products such as journal articles, may have strict limits on the number of citations they permit. Such limits are counter to our recommendation, and we recommend that publishers using strict limits for the number of citations add specific instructions regarding software citations to their author guidelines to not disincentivize software citation.

**Comment by jmcmurry** [comment]
+1

**Comment by danielskatz** [comment]
updated in https://github.com/force11/force11-scwg/commit/58d0dc42edfa1a0d707197dcc421cb5282ac779e

**Comment by olexandr-konovalov** [comment]
I haven't been publishing in places enforcing the limit on the number of citations, but quite often there was an implicit limit imposed by the total limit on the number of pages, e.g. in submissions to computer science conferences. For example, using LNCS style, a bibliography with 20 entries could easily use a whole page (out of e.g. 8-page limit).

I suggest that in case there is a page limit, the bibliography should not count towards this limit (moreover, there is a trend that conferences do not publish printed proceedings, but only provide an electronic publication).

**Comment by danielskatz** [comment]
Thanks.

I've added a sentence or two in https://github.com/force11/force11-scwg/commit/26a64b17c35c2c91bc3807b84d69ebe6b5b692d8 to address this.
