### ISSUE TITLE
new use case for funder?

### ISSUE THREAD

**Issue by strasser** [force11/force11-scwg#124]
As a funder, I want to measure the impact of the researchers I fund. This is a bit different from measuring the software itself - might require a new line in the table, with the requirement "authors"

**Comment by strasser** [comment]
Now realize this might be similar to the "Evaluator" line, but still might be worth calling out?

**Comment by roomthily** [comment]
I'd also wondered if being more explicit about the impact of the piece of
software cited vs the larger researcher/research group impact was important
to have here. Evaluator isn't necessarily tied to funders.

👍

Update: I misspoke. I was wondering if the software impact use case should be added as a Researcher use case:

> As a researcher, I want to analyze and provide altmetrics (or what-have-you) on my software project to a potential funding source to demonstrate its value to the community and secure additional funding.

On Sunday, April 17, 2016, Carly Strasser notifications@github.com wrote:

> Now realize this might be similar to the "Evaluator" line, but still might
> be worth calling out?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/force11/force11-scwg/issues/124#issuecomment-211067154

## 

Soren Scott
Research Coder
The Ronin Institute for Independent Scholarship
soren.scott@ronininstitute.org

just a head's up - taking a bit of a sabbatical so if i don't
get back to you right away, no worries.

**Comment by kyleniemeyer** [comment]
In response to @strasser, perhaps I can add "Funder" to the "Evaluate contributions of researcher" use case? (so that it would say `Evaluator, Funder` in the "Example stakeholder(s)" column)

For @roomthily's comment, would evaluating the software impact be different than the `Find citations of software` use case? I totally recognize that citations ≠ impact, but I'm wondering if they are similar enough for our purposes here.

**Comment by kyleniemeyer** [comment]
To try and make progress on this I added `Funder` to the `Evaluate contributions of researcher` use case in 3688a7187d18e3693b9625b834885c232abdf175, but open to other suggestions.

**Comment by roomthily** [comment]
@kyleniemeyer , I don't know? I read 'find citations' as more of a research activity from the principles document but that is probably not the intent there and not what's captured in the Use Cases document.

**Comment by kyleniemeyer** [comment]
Ah, perhaps the language could be improved then. The intent was to cover use cases where someone wanted to see who used (and cited) their software, so maybe a better description would be `Determine use/citations of software`, or something like that?

**Comment by roomthily** [comment]
@kyleniemeyer , works for me. Thanks!

**Comment by kyleniemeyer** [comment]
OK, hopefully everything in this issue has now been addressed with 6a3b17d7c802400d001aab5720d2c5b54a278b65, so I'll close it.
