### ISSUE TITLE
Educator use cases

### ISSUE THREAD

**Issue by eseiver** [force11/force11-scwg#127]
Think about how to give researchers credit for projects like https://github.com/jupyter/nbgrader

**Comment by kyleniemeyer** [comment]
Can you suggest a specific use case and the relevant metadata, either here or via a pull request?

One comment I have is that the principles are mainly focused on software citation for research, and not necessarily credit for software development in general—so one concern I would have is that this use case may be out of scope.

**Comment by kyleniemeyer** [comment]
(Although of course if there is a paper written about the educational advancement of using the software, then that would be in scope—but may be the same as use case 1.)

**Comment by kyleniemeyer** [comment]
Reminder to @eseiver (or anyone else watching), we should either close this or figure out the specifics of a new use case. I'm still leaning towards this not being significantly different than existing use cases, but open to (concrete) suggestions.

**Comment by danielskatz** [comment]
closed due to lack of recommendations
