### ISSUE TITLE
Is the question of when to cite an entirely community-specific decision?

### ISSUE THREAD

**Issue by maltman** [force11/force11-scwg#129]
The current document appears to declare of the question of what to cite/when to cite completely out of scope:

"The software citation principles do not define what software should be cited, but rather, how software should be cited."

The result appears to be to defer analysis to the differing scholarly communities.  The declaration of "importance" suggests that software should be cited more often, but again seems to imply that practices will be community specific.

Given the focus of the document on reproducibility, might it be possible to specify some necessary conditions (not sufficient) for citation in the principles, e.g:

"When a software is used directly in the process of establishing a published claim, that software should be cited. "

**Comment by danielskatz** [comment]
This text was in an early version, and we intentionally removed it based on the discussion on one of the working group phone calls.

So I'm going to close this issue, but it you want to reopen it and argue why this is needed, please feel free to.

**Comment by maltman** [comment]
I understand that since it was considered early and rejected, there may not be a consensus in this area:

 However, it may be worth reconsidering for the following reasons:
- there seemed to be many in today's workshop that had a minimum standard for reducibility in mind
- this next phase involves review by a larger audience -- highlighting those areas on which there is repeated discussion may be informative  for gathering input

**Comment by danielskatz** [comment]
I've changed the discussion text in 5.1 to include

> In general, we believe that software should be cited on the same basis as any other research product such as a paper or book; that is, authors should cite the appropriate set of software products just as they cite the appropriate set of papers, perhaps following the FORCE11 Data Citation Working Group principles, which state, “In scholarly literature, whenever and wherever a claim relies upon data, the corresponding data should be cited.” [10]

This has been applied in https://github.com/force11/force11-scwg/commit/f836404badc66c8c8a67c99fb06e5d6474feeff6
