### ISSUE TITLE
Principles should emphasize the need for a better way than citations to manage academic credit

### ISSUE THREAD

**Issue by cboettig** [force11/force11-scwg#131]
The current wording risks leaving the take-home as "All our issues with citation, credit, and reproducibility of software can be adequately addressed within the current model of academic citation practices."  We dismiss problems where the desire of credit conflict with the desire to track provenance by saying "that's a problem for academic citation in general, so to the extent that citation still fulfils both roles for papers, it can do so for data as well."

I fear this misses the orders of magnitude difference between how these problems manifest in software vs how they are dealt with in papers.  The quirks of citation practices which have been manageable in papers are exacerbated to a degree in which they may no longer be manageable.  

For instance: Both citations to both software and papers can suffer the 'wrapper problem' -- citing a review paper acknowledges the provenance of ideas but fails to allocate credit (citation count) to the originators.  Likewise citing a software client library acknowledges the provenance through it's dependency on the sever software system, but fails to transfer credit to it.  The difference is one of scale -- a closely knit research community can self-police a glaring omission of credit if an author cites a textbook in place of a citation classic of the field.  A reviewer is far less likely to be familiar with the original sources and underlying dependencies when they encounter a citation to a software wrapper around an existing algorithm or software system. 

Both software and papers share a tension in citing for provenance and citing for credit, but software has this issue in spades.  Provenance means fine-grained citation to particular version, credit means accumulating those citations against a single object.  Thin wrappers around fundamental dependencies are commonplace.  Authorship concepts are both more diverse and less governed by well-understood norms.

While we strive to offer practical guidelines that acknowledge the current incentive system of academic citation, a more modern system of assigning credit is sorely needed.  It is not that academic software needs a separate system from academic papers, but that it underscores the need to overhaul the system of credit for both.  

---

As discussed in the workshop, I'm working on a pull request along these lines, but comments & references welcome here.

**Comment by jmcmurry** [comment]
+1

**Comment by mfenner** [comment]
While I agree 100% with what @cboettig said, I worry that this is out of scope for the document. Maybe a paragraph explaining that citation in the scholarly literature is only part (even if currently a big part) of the academic credit system. But leave the more detailed discussion for another paper.

**Comment by cboettig** [comment]
@mfenner Yup, I basically said the same thing to @danielskatz  -- I meant this to be condensed to a few sentences that can go in the intro or conclusion and just communicate the gist of it (i.e. that these principles are not an endorsement of the current credit system, merely and acknowledgement of it).  It was just easier to write more first.  

Any suggestions on how best to summarize and where best to fold this into the larger narrative of the paper?

**Comment by kyleniemeyer** [comment]
I think this would be good fodder for a new paragraph-length discussion section (perhaps between `Access to software` and `Updates to this document`).

**Comment by danielskatz** [comment]
I think it's mostly part of section 2 - motivation, and maybe gets repeated as a sentence in conclusions/future work

**Comment by kyleniemeyer** [comment]
Yeah, I agree with @danielskatz. Perhaps some variation of 

> While we strive to offer practical guidelines that acknowledge the current incentive system of academic citation, a more modern system of assigning credit is sorely needed. It is not that academic software needs a separate system from academic papers, but that it underscores the need to overhaul the system of credit for both.

can be inserted in the motivation section, and then another sentence at the end. @cboettig?

**Comment by mfenner** [comment]
I like this paragraph.

**Comment by iliant** [comment]
I do agree too.

For papers value of credit varies form journal to journal in terms of let say impact factor.  Assigning credit or distributing credit is usually assumed equal between authors though this can be argued on.  Some experimental papers have hundreds of authors/contributors.  Software/code is different form papers and its impact is different too.  So one may argue that a different system is needed as credit for a piece software is not the same as credit for a paper, however both need to be acknowledged and assigned.  Thus the need to rethink the systems of credit for both.

Ilian

**Comment by danielskatz** [comment]
This is where my transitive credit idea (http://dx.doi.org/10.5334/jors.by) came in.  But I don't think we want to get into that full discussion here.

The paragraph Kyle wrote seems fairly good - maybe with some small wording changes:

While we strive to offer practical guidelines that acknowledge the current incentive system of academic citation, a more modern system of assigning credit is sorely needed. It is not that academic software needs a separate system from academic papers, but that the need for credit for application software underscores the need to overhaul the system of credit for all research products.

**Comment by kyleniemeyer** [comment]
OK, I'll incorporate that text into the document.

But, I do want to make sure @cboettig gets the credit for actually writing that paragraph 😃

**Comment by kyleniemeyer** [comment]
I just incorporated the above text into the motivations section via 6327e534d596dbeb6be2e119de6879fdc18ff913, and also added a sentence at the end. Please read over the additions and see if the placement is appropriate—I'm going to mark this as addressed, but we can of course edit the text I added.

**Comment by cboettig** [comment]
Very nice work, 6327e53 looks good to me. If only I could have y'all make all my ideas so clear!

**Comment by danielskatz** [comment]
I made another slight change in https://github.com/force11/force11-scwg/commit/eff87b2c382c88d02c2b8195d8eb71d83e6cf314
