### ISSUE TITLE
Additional research use case, historical/cultural analysis

### ISSUE THREAD

**Issue by maltman** [force11/force11-scwg#132]
Researcher wishes to  reproduce as closely as possible the experience of use of particular software in a particular context.

See library of congress Report: http://www.digitalpreservation.gov/multimedia/documents/PreservingEXE_report_final101813.pdf

**Comment by kyleniemeyer** [comment]
Does this overlap with the current use case "Reproduce analysis", where "reproduce" can involve "reproduction, replication, verification, validation, repeatability, and/or utility"?

**Comment by kyleniemeyer** [comment]
I'm continuing to feel that the suggested use case is the same (or overlaps) with the existing `Reproduce analysis` use case, and am going to mark this as to-be-closed, until I see additional discussion or a suggested change.
