### ISSUE TITLE
number of articles in table 1

### ISSUE THREAD

**Issue by olexandr-konovalov** [force11/force11-scwg#133]
Table 1 refers to 286 publications, but the 2nd paragraph of the section "Motivation" refers to the same source but regarding a random sample of 90 articles. Should it be 286 too?

**Comment by danielskatz** [comment]
Actually, the table refers to 286 publication mentions, and the text says these mentions came from 90 articles, which is perfectly reasonable, averaging about 3 software mentions per paper.

**Comment by olexandr-konovalov** [comment]
@danielskatz ah, now it makes perfect sense to me - thanks.
