### ISSUE TITLE
"Software citations should permit ... access to the software itself"

### ISSUE THREAD

**Issue by tompollard** [force11/force11-scwg#138]
Under the "Access" header, the [_data declaration_](https://www.force11.org/group/joint-declaration-data-citation-principles-final) states that:

> "Data citations should facilitate access to the data themselves"

Under the same header, the [software declaration](https://www.force11.org/software-citation-principles) states:

> "Software citations should **permit and** facilitate access to the software itself "

The addition of "permit" [suggests that](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=permit%20meaning) software citations should also grant the user with permission to access the software. Is this intentional? 

It doesn't seem like a good idea to make access a requirement for discovery, so "permit" might not be helpful in this sentence.

**Comment by danielskatz** [comment]
We started with the data declaration and modified it based on the software related work and working group discussion, so this was an intentional change, but we will revisit this issue.  Thanks for this comment.

**Comment by tompollard** [comment]
Thanks, I assume the "permit access to" is really intended for the later part of the sentence ("...to its associated metadata, documentation, etc...") rather than the software itself, so rephrasing might help?

It becomes clear later in the document (e.g. [section 5.9](https://www.force11.org/software-citation-principles#section5.9)) that the software may carry restrictions or may "no longer be available".
