### ISSUE TITLE
Granularity of the citation

### ISSUE THREAD

**Issue by satra** [force11/force11-scwg#140]
one of the key issues with any citation, whether document, individual, or software is the specificity of what is being cited. in the case of publications, there is almost zero specificity most of the time.

it's very easy to cite an entire package even though one function was used. part of this problem is being solved in the Python world through this project (https://github.com/duecredit/duecredit).

any citation should have the ability to specify more than just the obvious, but even the obvious would be a good starting point.

the citation/url should therefore allow for greater specificity within a code base. in general though, a provenance record of the workflow would be significantly more useful than a citation from a research perspective.

**Comment by danielskatz** [comment]
We agree that greater specificity is desirable in some cases, but we do not believe this rises to the level of what should be specified or discussed in the principles at this time.
