### ISSUE TITLE
Persistence of identifier vs. persistence of software

### ISSUE THREAD

**Issue by jklump** [force11/force11-scwg#143]
The persistence principle outlined in (4) is a key element in making software citeable. Where software has become part of the record of science not only the identifier and metadata of the software should be persistent, it should also be the goal to keep a persistent copy of the source code, where applicable. This links with the accessibility principle (5). 

There are still many open questions about how to resolve package dependencies in the long term, therefore I would not make the persistent access to code a hard requirement but may add something more specific towards preserving the record of science.

**Comment by kyleniemeyer** [comment]
Thanks for your comments! Our goal is for software citations to point to (persistent) archived source code, but we are not—nor could we—require this.
