### ISSUE TITLE
things we don't want to discuss further but should acknowledge

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-scwg#62]
peer review of cited software, or other review mechanisms

**Comment by jameshowison** [comment]
- specifying syntactical formats for references and in-text mentions. Rather the principles should enable looking at a software mention in a paper and seeing whether it meets the principles. We expect that publishers or groups like MLA will refer to the principles as they consider revisions to definitions.

**Comment by jameshowison** [comment]
Practices regarding which software should be cited (e.g., how far down the software stack)

**Comment by jameshowison** [comment]
- how software ought to be reviewed and how it should be trusted.

**Comment by roomthily** [comment]
The limits of citation metadata for provenance, for any reproducibility/replicability use case, vs the traditional provenance of a publication. Might be more an implementation discussion - for a given community, when is the citation "enough" and when should we consider a more expressive/detailed provenance trace (or set of traces) be made available? Does the citation capture the software artifact for a version and we look for the detailed variant information in some prov trace/methods document (or other community recognized thing)? 

I'll note that this comes up very fast in the data citation discussions, as well. 

For both, right now, it appears to be an issue around where those more granular provenance outputs are published and how they are referenced. 

But, a note acknowledging the use cases and their limits and goals wouldn't be inappropriate somewhere here (and would maybe kickstart that discussion in a more productive way in the data crowd :+1:).

**Comment by danielskatz** [comment]
the topics discussed in this issue, and their resolution, are:
software peer review - now discussed in a paragraph in section 5
syntax for software mentions in text - also discussed in section 5
what software should be cited - also discussed in section 5
limits of citation metadata for provenance - also discussion in section 5

Given this, I think  this issue can be closed.  If you have concerns, ideally raise them via a pull request on the document, and alternative, discuss them here.  I'll leave this issue open for a while to see if there are additional comments.
