### ISSUE TITLE
Van de Sompel et al, 5 attributes important for software metadata records?

### ISSUE THREAD

**Issue by ashleysa** [force11/force11-scwg#63]
Not sure if this made it into the earlier list of relevant materials, but I think this article gives a good introduction to research objects:

Van de Sompel, H., Payette, S., Erickson, J., Lagoze, C., & Warner, S. (2004). Rethinking scholarly communication: Building the system that scholars deserve. D-Lib Magazine, 10. Retrieved from http://www.dlib.org/dlib/september04/vandesompel/09vandesompel.html

They mentioned the following processes for multiple kinds of scholarly communication (data, code, paper, etc.) = registration, certification, awareness, archiving, rewarding.

Do we want to ensure those 5 attributes are relayed within the metadata?

**Comment by jameshowison** [comment]
Excellent, embarrassingly I hadn't seen that.

**Comment by kyleniemeyer** [comment]
I'm going to add some discussion of this either in the introduction/motivation or use cases section, although it likely won't be before the meeting tomorrow (Monday) morning.

**Comment by arfon** [comment]
> Not sure if this made it into the earlier list of relevant materials, but I think this article gives a good introduction to research objects:

Thanks @ashleysa. I'll be sure to add this to the background/previous work section too.

**Comment by kyleniemeyer** [comment]
After reading this more closely, I agree with @arfon that it should go in the background/previous work section. I just added a mention in commit ea0611b48535088f60f758952500e0e64d797b08, so I'm going to close this shortly.
