### ISSUE TITLE
Line 440 re: inaccessible versions

### ISSUE THREAD

**Issue by roomthily** [force11/force11-scwg#78]
For fast reference:

> As stated in the Persistence principle (\ref{principle:persistence}), we recognize that the commercial software version may no longer be available, but it still should be cited along with information about how it was accessed.

Should this be limited to commercial software only? I can think of a few 'open' hydro models that don't maintain older versions.

**Comment by danielskatz** [comment]
good point - I'll change this wording

**Comment by danielskatz** [comment]
I've removed "commercial" now, and will close this issue - feel free to reopen it if you don't think this is a sufficient response
