### ISSUE TITLE
Two typos, lines 301/401

### ISSUE THREAD

**Issue by roomthily** [force11/force11-scwg#79]
Line 301: noteable to notable

Line 401 to: 

Understanding these chains of knowledge and credit have been part of the history of science field for some time, though more recent work is suggesting more nuanced evaluation of the credit chains~\cite{casrai-credit, transitive_credit_json-ld}.

(insert 'the' for 'part of history of science')

**Comment by danielskatz** [comment]
I'm happy to make changes this way - you can also make pull requests if you wish (which would be slightly easier for me, and harder for you)

**Comment by danielskatz** [comment]
fixed.

**Comment by roomthily** [comment]
PRs as fine, I don't have permissions for the repo. No worries, thanks.
