### ISSUE TITLE
Change of wording of Software Importance

### ISSUE THREAD

**Issue by turingfan** [force11/force11-scwg#82]
(Sorry to be doing this late, I realise would have been better to contribute earlier.) 

I suggest a change of wording for Importance in section 1. 

The current wording is  "Software should be cited whenever and wherever a research product (such as a paper or derived software) relies upon it, specifically, as part of the standard reference list for that research product."

I feel the current text is too dogmatic about what software should be cited, and indeed is contradictory to the preamble text which says "For example, in this section we do not define what software should be cited, but how it should be cited."

To emphasise the point that software should be treated the same as anything else, I would suggest a revision to something like: 

Software should be cited on the same basis as any other research product such as a paper or book. That is, authors should see citing the appropriate set of software products as being as important as citing the appropriate set of papers.  Software citations should not be separated and should be part of the standard reference list for that research product

**Comment by turingfan** [comment]
BTW I can see my text is a bit longer which is bad. Happy for it to be cut down.

**Comment by iherman** [comment]
FWIW, I like the new formulation. Especially, 

> Software citations should not be separated and should be part of the standard reference list for that research product

is an important principle that we should indeed emphasize.

**Comment by danielskatz** [comment]
I will make this change

**Comment by turingfan** [comment]
Thanks! 

I think this does have a couple of knock on changes elsewhere in the document where the changed text was quoted in part.

**Comment by danielskatz** [comment]
I've just committed to address the changes later on - https://github.com/force11/force11-scwg/commit/15158b74f07d80accdbc0e8f7f642c18963974f5

Please see if there is anything else you think needs to be changed.
