### ISSUE TITLE
Please delete respecting software authors' requests.

### ISSUE THREAD

**Issue by turingfan** [force11/force11-scwg#83]
This may be controversial, and indeed I know it is from recent twitter discussions. But I feel it's important - or at least even if too controversial for agreement it's important to have the discussion. 

There is text in the draft which says 

"In addition, if the software authors ask that a paper should be cited, that should be respected."

I would like this sentence simply to be deleted.

I profoundly disagree with this point. I feel that software authors' opinion of whether their work should be cited is almost (but not completely) irrelevant. 

Not only that I think it's extremely important that the community understands that it is not up to software authors to demand citation. They can certainly request it, that is fine. But citation is part of the scientific process not a request that an author can insist on. This is NOT trying to demean the importance of software citation, it's actually equating it to all other forms of citation. I cite papers because it's the right thing to do, not because somebody asked me to. Nobody ever cites the papers that authors want to have cited: if they did then all papers ever written would cite all other papers ever written. 

The only area where I think the author's wish should be viewed as relevant is when it's a 50:50 call on whether to cite a piece of software or not.  I.e. I should cite the software I should cite it irrespective of the author's wish and - critically - if it's wrong to cite it then I shouldn't cite it irrespective of the author's wish. If it's an edge case then yes, it's reasonable to cite it if the author wants me to.

As an analogy, consider the very common case where a review comes back asking for 4 citations to somebody you strongly suspect to be the author of the review.  This is often seen at best as an embarassment or at worst as  a form of mild scientific misconduct. In my view software authors insisting on citation (as opposed to requesting it) is similar.

There is a long running dispute in this area in the case of Gnu parallel, for example.  The author insists on software citation for any paper that uses it, and explicitly asks people not to use it if they are not prepared to use it.  But there is no nuance: i.e. the author is not encouraging me to do so if it is right, but requiring me to do so if I use the software on a scientific paper.

**Comment by turingfan** [comment]
Deciding to rewrite this. Closing this version .... will open a new one.

**Comment by iliant** [comment]
A discussion is indeed important.

I have only spent 15 years of my lifetime as a software owner/author/architect but I can distinguish between what software authors need, want and plead, and what the impacts metrics provided form above require.  What I think is relevant what the licence terms state with respect to citation of relevant work.

Work citation can be demanded if need be but it cannot be policed as supported by "Nobody ever cites the papers that authors want to have cited: if they did then all papers ever written would cite all other papers ever written.".

Although it is important to software owners to get their work cited it is often the funding bodies contributing to the authors' projects and/or institutions that support the authors that necessitate this as a requirement for measuring impact.  In other words it is important to the organisations at least as much as to the authors.  When the word community is used it has to be identified which one...

It is ultimately the software users'/researchers' responsibility to respect the licensing terms and respect authors pleads to justify funding steams and work carried out in the used product/software.

The following comment is a criticism stemming form the publishers peer review system - "As an analogy, consider the very common case where a review comes back asking for 4 citations to somebody you strongly suspect to be the author of the review. This is often seen at best as an embarassment or at worst as a form of mild scientific misconduct. In my view software authors insisting on citation (as opposed to requesting it) is similar.".  It is relevant as it can be abused but not relevant to the creation of guidelines for citation of scientific/academic software.

Regards,

Ilian

**Comment by turingfan** [comment]
By the way I closed this issue but happy to have discussion here (or to quieten it down here and take it elsewhere) 

I believe strongly that software deserves more credit, but on the same basis as your point about my reviewing analogy, if funders are too focussed on citation, the same applies. I.e. what we should do is get funders and organisations to credit and fund software appropriately, AND write the correct software citation guidelines. Our guidelines should not be written for people who are behaving inappropriately, e.g. judging software mainly by its citation numbers.

I think the licence point is another discussion.  Obviously one should respect software licences one has agreed to, but I'm not sure if there are licences out there insisting on citation. (The case of Gnu parallel is ambiguous because it licenced under GPL and the author insists on citation, which are apparently incompatible.)
