### ISSUE TITLE
Additional considerations for contribution representation

### ISSUE THREAD

**Issue by mellybelly** [force11/force11-scwg#85]
Consider more advanced options to represent the relationship between people and various software contributions. e.g. section 4.3. 

1) Models such as those evolving in openRIF (formerly VIVO-ISF) https://github.com/openrif, which represent contribution types and roles towards any contribution type, and are not dependent on authoring of journals (though this is not the only source of such models)
2) Transitivity of contribution in packages that rely on one another and across versions. I quite like how this has been captured for various versions of data in the [HCLS dataset description](https://www.w3.org/2001/sw/hcls/notes/hcls-dataset/) - you can have a summary level representation that includes all contributions to date, or a version level distribution that has only contributions to that version.
3) Include reference to how software should be represented in CVs and biosketches to aid evaluation and review.

**Comment by danielskatz** [comment]
Can you make a pull request that indicates the language/changes you suggest?

**Comment by danielskatz** [comment]
@mellybelly reminder...

**Comment by kyleniemeyer** [comment]
I think point 2 is already addressed somewhat in Section 5.3, with some links (including to @danielskatz and @arfon's transitive credit paper).

Point 3 is important but I think beyond the scope of this document—but **absolutely** should be included in our follow-up implementation examples paper.

We don't really address contributor roles in this document because our focus is not really on credit (important, but also beyond the scope of this document I think).

**Comment by mellybelly** [comment]
I think the problem is that currently the references focus on credit focused on manuscript authoring, it would be great to include a few other references to work that aims to provision credit for other contribution types. Sorry i have been too busy to help much

**Comment by danielskatz** [comment]
We're not very good at responding to "it would be great" comments, but we're really excellent at merging pull requests :)

**Comment by danielskatz** [comment]
assuming the changes from @marijane were sufficient, and this can now be closed.
