### ISSUE TITLE
Additional references for section 4.3

### ISSUE THREAD

**Issue by iherman** [force11/force11-scwg#86]
1. I think that, at least for historical reasons, we should mention [DOAP](https://github.com/edumbill/doap/wiki). Although, afaik, Ed Dumbill does not pursue the project any more, it was, for a long time, almost the only game in town when it came to a more formal set of terms used in computer science (mainly in open source projects).
2. More recent is the set of terms defined by schema.org, namely [https://schema.org/SoftwareApplication](https://schema.org/SoftwareApplication). Knowing the importance schema.org has in the search space, this metadata set may have a great importance in practice.

**Comment by danielskatz** [comment]
Can you make a pull request to show exactly what you suggest be changed?

**Comment by iherman** [comment]
@danielskatz

Oh shoot, I made a minor mistake; I did not realize that I could commit to the repo directly; I thought what I had locally was my own fork and that I would then make a separate PR. Instead, I committed to the repo directly:

https://github.com/force11/force11-scwg/commit/aaf28c89bfe8d7bf37024f07d724a6ebbec83925

My apologies! I hope you can take it from there...

**Comment by danielskatz** [comment]
I think this looks fine - but a PR next time please...

**Comment by iherman** [comment]
> On 31 Mar 2016, at 13:47, Daniel S. Katz notifications@github.com wrote:
> 
> I think this looks fine - but a PR next time please...

Promised! :-)

Ivan
