### ISSUE TITLE
New background info

### ISSUE THREAD

**Issue by pgroth** [force11/force11-scwg#87]
I think it would be useful to cite: 
- NIST’s report on the economic impact of TREC [1] as motivation for why software citation is important 
-  "Assessing the impact of software on science: A bootstrapped learning of software entities in full-text papers" [2] - it has some nice stats on how much software is found in PLOS.. not OA :-( unfortunately

[1] http://trec.nist.gov/pubs/2010.economic.impact.pdf
[2] http://dx.doi.org/10.1016/j.joi.2015.07.012

**Comment by danielskatz** [comment]
Can you make a pull request with specific suggested edits?

**Comment by pgroth** [comment]
Done see pull request

**Comment by danielskatz** [comment]
thanks!
