### ISSUE TITLE
Confusion about Excel

### ISSUE THREAD

**Issue by turingfan** [force11/force11-scwg#90]
It's a small point but I find the text about Excel confusing in 5.1. That is, in the same paragraph we are told to cite Excel, not to cite Excel, and that the two statements are consistent. I realise this is a parody of what is said, but some clarification might be helpful. Even if it just meant changing the example of Excel to something else in the storing and plotting data example.

**Comment by kyleniemeyer** [comment]
I assume this is the text in question: `However, an illustrative example is the use of Microsoft Excel in research. We suggest that if Excel is used to simply store and plot data, it does not need to be cited, but if it is used for statistical analysis, it should be.`

I think that in the context of the preceding sentence `In general, we believe that any software on which a research product directly depends should be cited, if it significantly contributes to the research product.` it is hopefully clear that the statistical analysis refers to what the research product would depend on, vs. storing or plotting data.

That said, perhaps it could be rephrased for clarity—if you have an idea on how to improve, feel free to submit a pull request.

**Comment by danielskatz** [comment]
@turingfan Can we close this? Or do you want to suggest some specific change, ideally via a pull request?

**Comment by turingfan** [comment]
Yes close it. I don't have alternative text.
