### ISSUE TITLE
Related identifiers

### ISSUE THREAD

**Issue by mfenner** [force11/force11-scwg#98]
While we often need to cite a specific version of software, e.g. a release, we also need a way to cite the software in general, and to link multiple releases together. For this reason we need more than one persistent identifier for each software: a) a general one, and b) a specific one for each release. 

This issue is similar to what we see with versions for data. One use case would be to link all versions of a piece of software with a Zenodo DOI together, and then also associate the stars and forks of the code repository.

**Comment by danielskatz** [comment]
I'm tempted to say that this is a complex issue that is beyond the scope of this document, though I understand your use case, and think that it does need to be addressed somewhere (though perhaps not here). 

For one thing, I don't think we know what such a citation mechanism is, so I'm reluctant to say that we should do X.

Other thoughts are very welcome.

**Comment by cm-j0nes** [comment]
At STFC the Mantid software which is persistently identified using DOIs, there is a DOI for the concept, and then DOIs issued for each version, with relationships made between these different objects.  

I think there are different reasons for citing different software objects and this depends on the usage and so I don't think the citation principles should go into that level of detail. It should be clear what the cited object is.

**Comment by kyleniemeyer** [comment]
I don't necessarily want to complicate the discussion, but the approach described by @cm-j0nes (with different identifiers for concept and version) almost sounds like a good use case for citing a software paper vs. a specific version of the software itself.

The software paper may describe the concepts behind the software and overall implementation "theory", which may not really change between version—that can then be used as a "link" to all of the versions (somehow...). Of course, you would still need to cite the software (including version) directly when describing research that used the software.

**Comment by mfenner** [comment]
I think that we want to be generic, allowing the different scenarios (concept, software paper, release, etc.). The important point for me is that we want to capture that there is often more than one _thing_ describing the software.

**Comment by roomthily** [comment]
From the data citation side (at least from some members of the RDA dynamic data citation working group), I've heard proposals to manage the collection/granule citation with a kind of overloaded DOI. So the collection (one of the MODIS sets, for example) is assigned the DOI and then the cited subset is that DOI plus relevant bits appended to the end. Semi-structured and similar to a "Cool" URI:

`shoulder/id/MODIS/v25/some_granule_info/...`

I'll note that the indexers rarely come up in these conversations so whether that is a viable implementation for data or software? At least something to be aware of.

**Comment by danielskatz** [comment]
Given the choice between adding a new type object that could be treated like a DOI or changing the existing DOI, I strongly favor the former

**Comment by roomthily** [comment]
Sounded more like using the current DOI but with a very long ID string to capture the citation metadata. Like you should be able to understand the dynamic data citation solely from the DOI string. 

It is likely a moot point - DOIs aren't concordances, resolvers can't handle it, it raises authority issues...

**Comment by danielskatz** [comment]
subsubsection added in 5 (in https://github.com/force11/force11-scwg/commit/23208d255534b220ee3c0372b682a98128fb0f59) to address this.

**Comment by mfenner** [comment]
I liked the changed text. Thanks @danielskatz!

**Comment by cm-j0nes** [comment]
Me too!

Catherine
