### ISSUE TITLE
Reference lists

### ISSUE THREAD

**Issue by mfenner** [force11/force11-scwg#99]
In my personal view one of the shortcomings of the Joint Data Citation Principles is that they don't specifically mention that citations should go into reference lists. I am glad to see that the software citation principles mention reference lists. There might be a better place in the text for this, e.g. in an item 7 **interoperability**, again similar to the joint data citation principles.

**Comment by mfenner** [comment]
Because data might also be citing software, a more general term might be an alternative, e.g. "software that was cited should be included in the metadata of the citing work, for example in the reference list of a journal article".

**Comment by danielskatz** [comment]
I've made a change in the Importance principle to use some of your text in https://github.com/force11/force11-scwg/commit/533ecedd06f9c837b993240fbfe164849e52b9db  We can discuss if this should be moved to a new principle - it's not clear to me.

**Comment by danielskatz** [comment]
@mfenner: I'm marking this as "to be closed" - if you feel that there is more needed, please comment here.
